import { expect, test } from "@playwright/test";

/* Screenshots for the README.
 *
 * Generated by the same driver as the end-to-end tests, against the same live
 * stack, so what the README shows is what the app does. A hand-cropped
 * screenshot taken once and never regenerated is how a README ends up
 * advertising a version that no longer exists.
 *
 * Run with: npx playwright test screenshots --project=desktop
 */

test.describe("README screenshots", () => {
  // Desktop only. The mobile project would re-run every test and overwrite the
  // committed PNGs with Pixel-7-emulated renders; the mobile shot is taken here
  // with an explicit viewport instead.
  test.beforeEach(({}, testInfo) => {
    test.skip(testInfo.project.name !== "desktop", "screenshots are generated on desktop");
  });

  test("room with playlist", async ({ page }) => {
    await page.setViewportSize({ width: 1180, height: 1000 });
    await page.goto("/");
    await page.getByRole("button", { name: "Try the demo account" }).click();
    await page.getByRole("link", { name: /The car/ }).click();
    await page.getByRole("button", { name: /Build playlist|Regenerate/ }).click();
    await expect(page.locator("article").first()).toBeVisible({ timeout: 30_000 });
    await page.waitForTimeout(400);
    await page.screenshot({ path: "../../docs/images/room.png" });
  });

  test("per-member satisfaction", async ({ page }) => {
    await page.setViewportSize({ width: 1180, height: 760 });
    await page.goto("/");
    await page.getByRole("button", { name: "Try the demo account" }).click();
    await page.getByRole("link", { name: /The car/ }).click();
    await page.getByRole("button", { name: /Build playlist|Regenerate/ }).click();
    await expect(page.locator("article").first()).toBeVisible({ timeout: 30_000 });
    await page.getByRole("button", { name: "Predicted satisfaction per member" }).first().click();
    await page.waitForTimeout(400);
    await page.screenshot({ path: "../../docs/images/satisfaction.png" });
  });

  test("mobile", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 860 });
    await page.goto("/");
    await page.getByRole("button", { name: "Try the demo account" }).click();
    await page.getByRole("link", { name: /The car/ }).click();
    await page.getByRole("button", { name: /Build playlist|Regenerate/ }).click();
    await expect(page.locator("article").first()).toBeVisible({ timeout: 30_000 });
    await page.waitForTimeout(400);
    await page.screenshot({ path: "../../docs/images/mobile.png" });
  });

  test("onboarding", async ({ page }) => {
    await page.setViewportSize({ width: 1180, height: 860 });
    await page.goto("/");
    await page.getByRole("button", { name: "Try the demo account" }).click();
    await page.goto("/#/onboarding");
    await expect(page.getByRole("heading", { name: /What do you listen to/ })).toBeVisible();
    await page.waitForTimeout(600);
    await page.screenshot({ path: "../../docs/images/onboarding.png" });
  });
});
