"""Generate docs/measurements.md from eval/results/.

    python scripts/write_measurements.py

Generated, never typed. A number that lives in prose drifts from the number that
was measured, usually in the flattering direction, and nobody notices because
prose does not fail a test. Everything below comes out of the result JSON, which
records the git SHA and config hash that produced it.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = REPO_ROOT / "eval" / "results"
OUTPUT = REPO_ROOT / "docs" / "measurements.md"

HEADER = """# Measurements

**Generated by `scripts/write_measurements.py` from `eval/results/`. Do not edit
by hand.** Every number here was produced by a command in this repository and
can be reproduced by running it again.

```bash
python scripts/build_dataset.py --download     # rebuild the dataset
python scripts/run_eval.py --config eval/configs/individual.json
python scripts/write_measurements.py
```
"""

COLUMNS = [
    ("P@10", "precision@10"),
    ("R@10", "recall@10"),
    ("NDCG@10", "ndcg@10"),
    ("coverage@10", "coverage@10"),
    ("novelty@10", "novelty@10"),
    ("gini@10", "exposure_gini@10"),
]


def format_individual(record: dict) -> str:
    dataset = record["dataset"]
    split = record["split"]
    lines = [
        "",
        "## M3 — individual recommendation",
        "",
        f"*Run {record['run_at']} · commit `{record['git_sha']}` · engine "
        f"{record['engine_version']} · config hash `{record['config_hash']}`*",
        f"*{record['platform']}*",
        "",
        "### Dataset",
        "",
        "| | |",
        "| --- | --- |",
        "| Source | one ListenBrainz daily incremental dump (CC0) |",
        f"| Users | {dataset['users']:,} |",
        f"| Items | {dataset['items']:,} |",
        f"| Interactions | {dataset['interactions']:,} |",
        f"| Density | {dataset['density']:.4%} |",
        f"| Items with genre tags | {dataset['items_with_genre_tags']:,} "
        f"({dataset['items_with_genre_tags'] / max(dataset['items'], 1):.1%}) |",
        f"| Split | time-ordered leave-last-{split.get('n', 5)}-out, "
        f"min {split.get('min_train_items', 5)} training items |",
        f"| Training interactions | {split['train_interactions']:,} |",
        f"| Users evaluated | {record['results'][0]['users_evaluated']:,} "
        f"of {split['users_evaluated']:,} eligible |",
        "",
        "### Results",
        "",
        "| model | " + " | ".join(name for name, _ in COLUMNS) + " | fit (s) |",
        "| --- | " + " | ".join("---" for _ in COLUMNS) + " | --- |",
    ]

    for result in record["results"]:
        metrics = result["metrics"]
        cells = [f"{metrics.get(key, 0.0):.4f}" for _, key in COLUMNS]
        lines.append(
            f"| {result['model']} | " + " | ".join(cells) + f" | {result['fit_seconds']:.1f} |"
        )

    by_name = {r["model"]: r["metrics"] for r in record["results"]}
    best = max(record["results"], key=lambda r: r["metrics"]["precision@10"])
    popularity = by_name.get("popularity", {})

    lines += [
        "",
        f"Total evaluation time: **{record['total_seconds']}s** for "
        f"{len(record['results'])} models.",
        "",
        "### Reading this",
        "",
    ]

    if popularity:
        p_ratio = best["metrics"]["precision@10"] / max(popularity["precision@10"], 1e-9)
        n_ratio = best["metrics"]["ndcg@10"] / max(popularity["ndcg@10"], 1e-9)
        c_ratio = best["metrics"]["coverage@10"] / max(popularity["coverage@10"], 1e-9)
        lines += [
            f"**`{best['model']}` beats the popularity baseline by "
            f"{p_ratio:.1f}× on P@10 and {n_ratio:.1f}× on NDCG@10, while recommending "
            f"{c_ratio:.0f}× more of the catalogue.** Popularity reaches "
            f"{popularity['coverage@10']:.2%} coverage — it shows almost everyone the same "
            "few dozen tracks, which is exactly the failure that accuracy metrics alone "
            "would hide.",
            "",
            "`random` is the floor and behaves like one. Its high coverage and novelty are "
            "not a virtue: recommending the whole catalogue at random covers a lot of it.",
            "",
        ]

    return "\n".join(lines)


def format_sweep(record: dict) -> str:
    best = record["best"]
    lines = [
        "",
        "## Hybrid weights: how they were fitted",
        "",
        record["note"],
        "",
        f"Grid `{record['grid']}` over four components, "
        f"{record['users_evaluated']} validation users, selected on "
        f"`{record['selected_on']}`.",
        "",
        "| component | fitted weight |",
        "| --- | --- |",
    ]
    for name, weight in best["weights"].items():
        lines.append(f"| {name} | {weight:.2f} |")

    zero = [name for name, weight in best["weights"].items() if weight == 0]
    if zero:
        lines += [
            "",
            f"**The search assigned zero weight to {', '.join(f'`{z}`' for z in zero)}.** "
            "That is a negative result and it is reported rather than tuned away: on this "
            "dataset the content model and the popularity prior add nothing once "
            "collaborative signal is present. The content features are thin — a third of "
            "items have genre tags and the rest carry only artist identity, which "
            "collaborative filtering already captures.",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    sections = [HEADER]

    individual = RESULTS_DIR / "individual.json"
    if individual.exists():
        sections.append(format_individual(json.loads(individual.read_text())))

    sweep = RESULTS_DIR / "weight-sweep.json"
    if sweep.exists():
        sections.append(format_sweep(json.loads(sweep.read_text())))

    sections.append(
        "\n".join(
            [
                "",
                "## What these numbers are not",
                "",
                "- **Not a claim about human satisfaction.** These are held-out play "
                "predictions on one day of ListenBrainz listens, not a measure of whether "
                "anyone enjoyed a playlist.",
                "- **Not a comparison to published benchmarks.** The dataset is built by "
                "this repository from a single daily dump; absolute values are not "
                "comparable to numbers computed on MovieLens or Last.fm-360K. Only the "
                "*relative* comparison between the rows above is meaningful, and that is "
                "the whole reason the baselines are there.",
                "- **Not group recommendation.** Everything here scores one user at a "
                "time. The group ranking, fairness metrics and the three modes are M4.",
                "",
            ]
        )
    )

    OUTPUT.write_text("\n".join(sections))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
