"""Generate docs/measurements.md from eval/results/.

    python scripts/write_measurements.py

Generated, never typed. A number that lives in prose drifts from the number that
was measured, usually in the flattering direction, and nobody notices because
prose does not fail a test. Everything below comes out of the result JSON, which
records the git SHA and config hash that produced it.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = REPO_ROOT / "eval" / "results"
OUTPUT = REPO_ROOT / "docs" / "measurements.md"

HEADER = """# Measurements

**Generated by `scripts/write_measurements.py` from `eval/results/`. Do not edit
by hand.** Every number here was produced by a command in this repository and
can be reproduced by running it again.

```bash
python scripts/build_dataset.py --download     # rebuild the dataset
python scripts/run_eval.py --config eval/configs/individual.json
python scripts/write_measurements.py
```
"""

COLUMNS = [
    ("P@10", "precision@10"),
    ("R@10", "recall@10"),
    ("NDCG@10", "ndcg@10"),
    ("coverage@10", "coverage@10"),
    ("novelty@10", "novelty@10"),
    ("gini@10", "exposure_gini@10"),
]


def format_individual(record: dict) -> str:
    dataset = record["dataset"]
    split = record["split"]
    lines = [
        "",
        "## M3 — individual recommendation",
        "",
        f"*Run {record['run_at']} · commit `{record['git_sha']}` · engine "
        f"{record['engine_version']} · config hash `{record['config_hash']}`*",
        f"*{record['platform']}*",
        "",
        "### Dataset",
        "",
        "| | |",
        "| --- | --- |",
        f"| Source | {record.get('_dataset_label', 'unknown')} |",
        f"| Users | {dataset['users']:,} |",
        f"| Items | {dataset['items']:,} |",
        f"| Interactions | {dataset['interactions']:,} |",
        f"| Density | {dataset['density']:.4%} |",
        f"| Items with genre tags | {dataset['items_with_genre_tags']:,} "
        f"({dataset['items_with_genre_tags'] / max(dataset['items'], 1):.1%}) |",
        f"| Split | time-ordered leave-last-{split.get('n', 5)}-out, "
        f"min {split.get('min_train_items', 5)} training items |",
        f"| Training interactions | {split['train_interactions']:,} |",
        f"| Users evaluated | {record['results'][0]['users_evaluated']:,} "
        f"of {split['users_evaluated']:,} eligible |",
        "",
        "### Results",
        "",
        "| model | " + " | ".join(name for name, _ in COLUMNS) + " | fit (s) |",
        "| --- | " + " | ".join("---" for _ in COLUMNS) + " | --- |",
    ]

    for result in record["results"]:
        metrics = result["metrics"]
        cells = [f"{metrics.get(key, 0.0):.4f}" for _, key in COLUMNS]
        lines.append(
            f"| {result['model']} | " + " | ".join(cells) + f" | {result['fit_seconds']:.1f} |"
        )

    by_name = {r["model"]: r["metrics"] for r in record["results"]}
    best = max(record["results"], key=lambda r: r["metrics"]["precision@10"])
    popularity = by_name.get("popularity", {})

    lines += [
        "",
        f"Total evaluation time: **{record['total_seconds']}s** for "
        f"{len(record['results'])} models.",
        "",
        "### Reading this",
        "",
    ]

    if popularity:
        p_ratio = best["metrics"]["precision@10"] / max(popularity["precision@10"], 1e-9)
        n_ratio = best["metrics"]["ndcg@10"] / max(popularity["ndcg@10"], 1e-9)
        c_ratio = best["metrics"]["coverage@10"] / max(popularity["coverage@10"], 1e-9)
        lines += [
            f"**`{best['model']}` beats the popularity baseline by "
            f"{p_ratio:.1f}× on P@10 and {n_ratio:.1f}× on NDCG@10, while recommending "
            f"{c_ratio:.0f}× more of the catalogue.** Popularity reaches "
            f"{popularity['coverage@10']:.2%} coverage — it shows almost everyone the same "
            "few dozen tracks, which is exactly the failure that accuracy metrics alone "
            "would hide.",
            "",
            "`random` is the floor and behaves like one. Its high coverage and novelty are "
            "not a virtue: recommending the whole catalogue at random covers a lot of it.",
            "",
        ]

    return "\n".join(lines)


def format_sweep(record: dict) -> str:
    best = record["best"]
    lines = [
        "",
        "## Hybrid weights: how they were fitted",
        "",
        record["note"],
        "",
        f"Grid `{record['grid']}` over four components, "
        f"{record['users_evaluated']} validation users, selected on "
        f"`{record['selected_on']}`.",
        "",
        "| component | fitted weight |",
        "| --- | --- |",
    ]
    for name, weight in best["weights"].items():
        lines.append(f"| {name} | {weight:.2f} |")

    zero = [name for name, weight in best["weights"].items() if weight == 0]
    if zero:
        lines += [
            "",
            f"**The search assigned zero weight to {', '.join(f'`{z}`' for z in zero)}.** "
            "That is a negative result and it is reported rather than tuned away: on this "
            "dataset the content model and the popularity prior add nothing once "
            "collaborative signal is present. The content features are thin — a third of "
            "items have genre tags and the rest carry only artist identity, which "
            "collaborative filtering already captures.",
            "",
        ]
    return "\n".join(lines)


GROUP_COLUMNS = [
    ("held mean", "held_mean"),
    ("held served", "held_served"),
    ("held gini", "held_gini"),
    ("proxy mean", "proxy_mean"),
    ("proxy min", "proxy_min"),
    ("veto viol.", "veto_violations"),
    ("max artist", "max_artist_share"),
    ("novelty", "novelty"),
]


def format_group(record: dict) -> str:
    groups = record["groups"]
    lines = [
        "",
        f"## M4 -- group recommendation on {record.get('_dataset_label', 'the dataset')}",
        "",
        f"*Run {record['run_at']} \u00b7 commit `{record['git_sha']}` \u00b7 engine "
        f"{record['engine_version']} \u00b7 config hash `{record['config_hash']}`*",
        f"*{record['platform']}*",
        "",
        f"{groups['total']} synthetic groups of "
        f"{record['config'].get('group_sizes', [3, 4, 5, 6])} members, "
        f"{record['k']} tracks each.",
        "",
        "| group kind | groups | mean size | mean cohesion |",
        "| --- | --- | --- | --- |",
    ]
    for kind, stats in groups["by_kind"].items():
        lines.append(
            f"| {kind} | {stats['groups']} | {stats['mean_size']:.1f} | "
            f"{stats['mean_cohesion']:.4f} |"
        )

    lines += [
        "",
        "Cohesion is mean pairwise Jaccard similarity of members' training "
        "histories, reported so the labels can be checked rather than trusted.",
        "",
        "### Results (all groups)",
        "",
        "| strategy | " + " | ".join(n for n, _ in GROUP_COLUMNS) + " |",
        "| --- | " + " | ".join("---" for _ in GROUP_COLUMNS) + " |",
    ]
    for result in record["results"]:
        cells = [f"{result['overall'].get(key, 0.0):.4f}" for _, key in GROUP_COLUMNS]
        lines.append(f"| {result['strategy']} | " + " | ".join(cells) + " |")

    lines += ["", "### Reading this", ""]

    comparisons = record.get("comparisons", {}).get("consensus_vs_average_score", {})
    if comparisons:
        lines += [
            "Differences against the `average-score` baseline, **paired over the "
            "same groups** with a 10,000-sample bootstrap. An interval containing "
            "zero means the two strategies are not distinguishable at this sample "
            "size.",
            "",
            "| metric | consensus \u2212 average-score | 95% CI | distinguishable? |",
            "| --- | --- | --- | --- |",
        ]
        for metric, comparison in comparisons.items():
            verdict = "**yes**" if comparison.get("significant") else "no"
            lines.append(
                f"| {metric} | {comparison['mean_difference']:+.4f} | "
                f"[{comparison['ci_low']:+.4f}, {comparison['ci_high']:+.4f}] | {verdict} |"
            )
        lines += [
            "",
            "**What the group layer demonstrably buys: no veto violations, "
            "markedly less repetition, and a higher proxy floor.** All three are "
            "significant here and on the other dataset.",
            "",
            "**What it does not buy is held-out accuracy, in either direction.** "
            "The accuracy intervals straddle zero. That cuts both ways and both "
            "are worth saying: the fairness and repetition guarantees are real, "
            "and they cost nothing measurable -- but no accuracy *gain* can be "
            "claimed from these numbers either.",
            "",
        ]

    lines += [
        "### Per-kind breakdown",
        "",
        "Roughly 50 groups per kind, so **these cells are noisy and no conclusion "
        "should be drawn from a single one**. An earlier version of this document "
        "read a per-kind gap of ~0.01 as evidence that the group layer wins on "
        "adversarial groups; the paired intervals above show that gap is inside "
        "the noise, and the sign of it reverses on the other dataset. The table "
        "stays because the *large* differences in it -- veto violations and "
        "repetition -- are real.",
        "",
    ]
    kinds = sorted({k for r in record["results"] for k in r["by_kind"]})
    for metric_label, metric_key in [
        ("members reached (held_served)", "held_served"),
        ("proxy floor (proxy_min)", "proxy_min"),
        ("veto violations", "veto_violations"),
    ]:
        lines += [
            f"**{metric_label}**",
            "",
            "| strategy | " + " | ".join(kinds) + " |",
            "| --- | " + " | ".join("---" for _ in kinds) + " |",
        ]
        for result in record["results"]:
            cells = [
                f"{result['by_kind'].get(kind, {}).get(metric_key, 0.0):.4f}" for kind in kinds
            ]
            lines.append(f"| {result['strategy']} | " + " | ".join(cells) + " |")
        lines.append("")

    return "\n".join(lines)


def format_mode_sweep(record: dict) -> str:
    lines = [
        "",
        "## Mode parameters: how they were fitted",
        "",
        record["note"],
        "",
        f"{record['combinations_evaluated']} combinations on "
        f"{record['validation_groups']} validation groups.",
        "",
        "| mode | objective | alpha | tau_veto | lambda_fair | lambda_nov |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for mode_name, row in record["selected"].items():
        p = row["params"]
        objective = record["objectives"].get(mode_name, "")
        lines.append(
            f"| {mode_name} | {objective} | {p['alpha']:.2f} | {p['tau_veto']:.2f} | "
            f"{p['lambda_fair']:.2f} | {p['lambda_nov']:.2f} |"
        )

    lines += [
        "",
        "**Two findings worth stating.** Every mode wanted `lambda_fair = 0.45`: "
        "serving the least-served member helps regardless of which objective is "
        "being maximised, which was not the expectation -- fairness was designed "
        "as a Fair Rotation feature, not a general one.",
        "",
        "And the unconstrained search chose `tau_veto = 0.00` for fair_rotation. "
        "That maximises the proxy floor by deleting the veto and enlarging the "
        "candidate pool -- trading a product guarantee (no member sits through a "
        "track they strongly object to) for a metric. **The fit was overridden "
        "and tau held at 0.35**, which is recorded here rather than quietly "
        "applied.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    sections = [HEADER]

    for individual_file, dataset_label in (
        ("individual.json", "ListenBrainz slice"),
        ("individual-ml1m.json", "MovieLens-1M"),
    ):
        path = RESULTS_DIR / individual_file
        if path.exists():
            record = json.loads(path.read_text())
            record["_dataset_label"] = dataset_label
            sections.append(format_individual(record))

    sweep = RESULTS_DIR / "weight-sweep.json"
    if sweep.exists():
        sections.append(format_sweep(json.loads(sweep.read_text())))

    for group_file, dataset_label in (
        ("group.json", "ListenBrainz slice"),
        ("group-ml1m.json", "MovieLens-1M"),
    ):
        path = RESULTS_DIR / group_file
        if path.exists():
            record = json.loads(path.read_text())
            record["_dataset_label"] = dataset_label
            sections.append(format_group(record))

    mode_sweep = RESULTS_DIR / "mode-sweep.json"
    if mode_sweep.exists():
        sections.append(format_mode_sweep(json.loads(mode_sweep.read_text())))

    sections.append(
        "\n".join(
            [
                "",
                "## What these numbers are not",
                "",
                "- **Not a claim about human satisfaction.** These are held-out play "
                "predictions on one day of ListenBrainz listens, not a measure of whether "
                "anyone enjoyed a playlist.",
                "- **Not a comparison to published benchmarks.** The dataset is built by "
                "this repository from a single daily dump; absolute values are not "
                "comparable to numbers computed on MovieLens or Last.fm-360K. Only the "
                "*relative* comparison between the rows above is meaningful, and that is "
                "the whole reason the baselines are there.",
                "- **Group metrics inherit that caveat and add one.** `held_*` "
                "numbers are grounded in real held-out plays, but `proxy_*` numbers "
                "use the model's own predicted satisfaction and so partly measure "
                "the model agreeing with itself. Where the two disagree, the held-out "
                "figure is the honest one.",
                "- **`held_gini` is not a fairness win on its own.** At this sparsity "
                "most members get zero hits, and a strategy that serves nobody scores "
                "a perfect Gini because everyone is equally unserved -- which is why "
                "`popularity` has the lowest inequality in the table and is still the "
                "worst strategy in it.",
                "",
            ]
        )
    )

    OUTPUT.write_text("\n".join(sections))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
